### ISSUE TITLE
ComfyUI-Manager

### ISSUE THREAD

**Issue by ronowe** [ciri/comfyui-model-downloader#2]
Hi,
This node is great but it is no available on ComfyUI-Manager. For example I can't use it on openart.ai because it will not download it to the nodes. Can you  send pull request to  ComfyUI-Manager?
Best regards, Daniel

**Comment by ciri** [comment]
Thanks for the suggestion! I’ve created a pull request to add the ComfyUI Model Downloader node to ComfyUI-Manager. You can view and track the request here: [https://github.com/ltdrdata/ComfyUI-Manager/pull/1198](https://github.com/ltdrdata/ComfyUI-Manager/pull/1198).
